# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/simpliplay"
    schedule:
      interval: "daily"
    versioning-strategy: increase

    # block major version updates for the builder cuz electron-builder *usually* has breaking changes with major version updates
    # and breaks some builds; especially for windows
    ignore:
      - dependency-name: "electron-builder"
        update-types: ["version-update:semver-major"]
