name: Test on Linux

on:
  workflow_call:

jobs:
  test-linux:
    name: Test ${{ matrix.arch }}
    runs-on: ${{ matrix.arch == 'x86_64' && 'ubuntu-latest' || 'ubuntu-22.04-arm' }}
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        env:
          PKG_ASOUND: ${{ matrix.arch == 'x86_64' && 'libasound2t64' || 'libasound2' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb libgbm1 $PKG_ASOUND

      - name: Download artifact
        env:
          SEARCH_ARCH: ${{ matrix.arch == 'x86_64' && 'x64' || matrix.arch }}
          GH_TOKEN: ${{ github.token }}
        run: |
          gh run download ${{ github.run_id }} --pattern "*linux*${SEARCH_ARCH}*" --dir test-dist

      - name: Run launch test
        run: |
          appimage=$(find test-dist -name "*.AppImage" | head -n 1)
          chmod +x "$appimage"
          "$appimage" --appimage-extract
          
          exec_path="./squashfs-root/SimpliPlay"
          chmod +x "$exec_path"

          echo "starting x64/arm64 test (15s)"
          dbus-run-session -- xvfb-run --auto-servernum "$exec_path" --no-sandbox &
          our_pid=$!
          
          sleep 15
          if kill -0 $our_pid 2>/dev/null; then
            echo "app is alive. terminating..."
            kill $our_pid
          else
            echo "app crashed or closed too soon"
            exit 1
          fi
