name: Build macOS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths-ignore:
      - '.github/workflows/dependabot-bump.yml'
      - '.github/workflows/dependabot.yml'
      - 'README.md'             # Ignore documentation
      - '.gitignore'            # Ignore git settings

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Clean up caches
        run: |
          npm cache clean --force
          rm -rf ~/Library/Caches/electron-builder
        working-directory: simpliplay

      - name: Install dependencies
        run: npm install
        working-directory: simpliplay

      - name: Create DMGs
        run: npx electron-builder --mac --x64 --arm64 --universal
        working-directory: simpliplay

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: builds
          # Upload only the final signed DMGs
          path: simpliplay/dist/*.dmg
