name: Build macOS

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Clean up caches
        run: |
          npm cache clean --force
          rm -rf ~/Library/Caches/electron-builder
        working-directory: simpliplay

      - name: Install deps
        run: npm install
        working-directory: simpliplay

      - name: Create DMGs
        run: npx electron-builder --mac --x64 --arm64 --universal
        working-directory: simpliplay

      - name: Upload production builds
        uses: actions/upload-artifact@v6
        with:
          name: builds
          path: simpliplay/dist/*.dmg

      # - name: Prepare test ZIP
      #   run: |
      #     # ditto to preserve the mac metadata
      #     cd simpliplay/dist
      #     # zip the app into an uncomfy backpack
      #     find . -name "SimpliPlay.app" -exec ditto -c -k --sequesterRsrc --keepParent "{}" test-app.zip \;

      # - name: Upload testing binaries
      #   uses: actions/upload-artifact@v6
      #   with:
      #     name: test-artifacts
      #     path: simpliplay/dist/test-app.zip


