name: Build Linux

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths-ignore:
      - '.github/workflows/dependabot-bump.yml'
      - '.github/workflows/dependabot.yml'
      - 'README.md' #ignore readme
      - '.gitignore' #ignore the gitignore that is the file that ignores other files

jobs:
  build_x64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm install
        working-directory: simpliplay

      - name: Build Snap and AppImage
        run: npx electron-builder --linux snap AppImage --x64
        working-directory: simpliplay

      - name: Install Flatpak tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential flatpak flatpak-builder
        continue-on-error: true

      - name: Create unpacked build for Flatpak
        run: npx electron-builder --linux --x64 --dir
        working-directory: simpliplay
        
      - name: Patch package.json
        run: |
          # save OG package json
          cp simpliplay/package.json simpliplay/package.json.orig
          # Check if jq is installed; if not, install it
          if ! command -v jq &> /dev/null
          then
            echo "jq not found, installing..."
            sudo apt-get update
            sudo apt-get install -y jq
          fi
          # patch package.json for older electron for compat
          jq '.devDependencies.electron="39.0.0"' simpliplay/package.json.orig > simpliplay/package.flatpak.json
          # Replace package.json for Flatpak build
          mv simpliplay/package.flatpak.json simpliplay/package.json

      - name: Build Flatpak
        run: npx electron-builder --linux flatpak --x64
        working-directory: simpliplay
        continue-on-error: true

      - name: Restore package.json
        run: mv simpliplay/package.json.orig simpliplay/package.json # redundant for now but might be useful in future

      - uses: actions/upload-artifact@v4
        with:
          name: linux-x64-snap
          path: simpliplay/dist/*.snap

      - uses: actions/upload-artifact@v4
        with:
          name: linux-x64-appimage
          path: simpliplay/dist/*.AppImage
          
      - uses: actions/upload-artifact@v4
        with:
          name: linux-x64-flatpak
          path: simpliplay/dist/*.flatpak
        continue-on-error: true

  build_arm64:
    runs-on: ubuntu-22.04-arm
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Use arm64 package.json instead of x64
        run: |
          mv simpliplay/package.json simpliplay/package-unused.json
          mv simpliplay/package-arm64-linux.json simpliplay/package.json

      - run: npm install
        working-directory: simpliplay

      - run: npx electron-builder --linux AppImage --arm64
        working-directory: simpliplay

      # the below is to prevent snapcraft from crashing
      # for some reason it does not cope without these deps
      # on arm64 and armv7 anyway

      - name: Update package listings and install libgdk-pixbuf
        run: sudo apt-get update && sudo apt-get install --only-upgrade libgdk-pixbuf-2.0-0

      - name: Install Snapcraft CLI
        run: sudo snap install snapcraft --classic

      - name: Install GNOME packages
        run: sudo snap install gnome-3-28-1804

      - name: Install GTK theme stuff
        run: sudo snap install gtk-common-themes

      - name: Install core22 snap
        run: sudo snap install core22

      - name: Build Snap
        run: SNAPCRAFT_BUILD_ENVIRONMENT=host USE_SYSTEM_FPM=true npx electron-builder --linux snap --arm64
        working-directory: simpliplay

      - name: Install Flatpak tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential flatpak flatpak-builder
        continue-on-error: true

      - name: Patch package.json for Flatpak
        run: |
          # Save og
          cp simpliplay/package.json simpliplay/package.json.orig
          # Check if jq is installed; if not, install it
          if ! command -v jq &> /dev/null
          then
            echo "jq not found, installing..."
            sudo apt-get update
            sudo apt-get install -y jq
          fi
          # patch the json to use older electron for compat
          jq '.devDependencies.electron="39.0.0"' simpliplay/package.json.orig > simpliplay/package.flatpak.json
          # replace package.json for flatpak build cuz electron-builder is unfortunately
          # picky regarding flatpaks
          mv simpliplay/package.flatpak.json simpliplay/package.json

      - name: Restore package.json
        run: mv simpliplay/package.json.orig simpliplay/package.json

      - name: Create unpacked build for Flatpak
        run: npx electron-builder --linux --arm64 --dir
        working-directory: simpliplay

      - name: Build Flatpak
        run: | 
          #echo "file struct below:"
          #ls
          
          #if ! pwd | grep -q "simpliplay"; then
            #cd simpliplay
          #fi
          if [ ! -d node_modules ]; then
            echo "node_modules wasn't found, will install deps now"
            npm install
          fi
          npx electron-builder --linux flatpak --arm64
        working-directory: simpliplay
        continue-on-error: true

      - uses: actions/upload-artifact@v4
        with:
          name: linux-arm64-appimage
          path: simpliplay/dist/*.AppImage
          
      - uses: actions/upload-artifact@v4
        with:
          name: linux-arm64-snap
          path: simpliplay/dist/*.snap

      - uses: actions/upload-artifact@v4
        with:
          name: linux-arm64-flatpak
          path: simpliplay/dist/*.flatpak
        continue-on-error: true

  build_i386:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
  
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Prepare i386 package.json
        run: |
          # save og package.json
          cp simpliplay/package.json simpliplay/package.json.orig
      
          # is jq installed?
          if ! command -v jq &> /dev/null
          then
            echo "jq not found, installing..."
            sudo apt-get update
            sudo apt-get install -y jq
          fi
      
          # patch package.json to use Electron v3.1
          jq '.devDependencies.electron="3.1.13"' simpliplay/package.json.orig > simpliplay/package.i386.json
      
          # replace package.json for the i386 build
          mv simpliplay/package.i386.json simpliplay/package.json
  
      - run: npm install
        working-directory: simpliplay
  
      - name: Build AppImage i386
        run: npx electron-builder --linux AppImage --ia32
        working-directory: simpliplay
  
      - uses: actions/upload-artifact@v4
        with:
          name: linux-i386-appimage
          path: simpliplay/dist/*.AppImage

  build_armv7:
    runs-on: ubuntu-22.04-arm
    steps:
      - uses: actions/checkout@v4
  
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install QEMU for ARMv7 emulation
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static binfmt-support
          # register arm emulation to FOOL snapcraft cli
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes || true

      - name: Install dependencies
        run: npm install
        working-directory: simpliplay

      - name: Build ARMv7 AppImage
        run: npx electron-builder --linux AppImage --armv7l
        working-directory: simpliplay
  
      - name: Upload ARMv7 AppImage
        uses: actions/upload-artifact@v4
        with:
           name: linux-armv7-appimage
           path: simpliplay/dist/*.AppImage

      # the below is to prevent snapcraft from crashing
      # for some reason it does not cope without these deps
      # on arm64 and armv7 anyway

      - name: Update package listings and install libgdk-pixbuf
        run: sudo apt-get update && sudo apt-get install --only-upgrade libgdk-pixbuf-2.0-0

      - name: Install Snapcraft CLI
        run: sudo snap install snapcraft --classic

      - name: Install GNOME packages
        run: sudo snap install gnome-3-28-1804

      - name: Install GTK theme stuff
        run: sudo snap install gtk-common-themes

      - name: Install core22 snap
        run: sudo snap install core22

      - name: Build ARMv7 Snap
        run: npx electron-builder --linux snap --armv7l
        working-directory: simpliplay
        
      - name: Upload ARMv7 Snap         
        uses: actions/upload-artifact@v4
        with:
          name: linux-armv7l-v2-snap
          path: simpliplay/dist/*.snap

  start-linux-tests:
    name: Start Linux Tests
    needs: [build_x64, build_arm64, build_armv7]
    uses: ./.github/workflows/test-linux.yml
