name: Draft Release
on:
  workflow_dispatch:
    inputs:
        release_notes:
          description: "Anything's changed? The release notes are in Markdown btw."
          required: false
          default: "Just a regular release. Not too many changes :D"
  workflow_call:

jobs:
  create-draft-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          # fetches all the history instead of just
          # one commit by default
          fetch-depth: 0 

      - name: Prepare folder(s)
        run: mkdir -p all-artifacts

      - name: Download artifacts
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh run download --dir all-artifacts

      - name: Generate changelog
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          #TODO: get gh api working
          git log -n 10 --format="- %s" > raw.md

          # pipe into changelog md for release step
          # to take over
          {
            echo "## Release Notes"
            echo "${{ inputs.release_notes }}"
            echo ""
          } > "${{ github.workspace }}/CHANGELOG.md"

      - name: Create draft release and upload assets
        uses: softprops/action-gh-release@v3
        with:
          tag_name: "draft-${{ github.run_number }}"
          name: "Release draft-${{ github.run_number }}"
          draft: true
          body_path: CHANGELOG.md
          files: |
            all-artifacts/**/*.exe
            all-artifacts/**/*.dmg
            all-artifacts/**/*.flatpak
            all-artifacts/**/*.AppImage
          token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
