name: Handle manual dep updates
on:
  pull_request:
    types: [labeled]

jobs:
  close-prs:
    if: github.event.label.name == 'manual-upgrade'
    runs-on: ubuntu-latest
    steps:
      - name: Close dependabot PRs
        run: |
          title="${{ github.event.pull_request.title }}"

          if [[ "$title" == *"electron-builder"* ]]; then
            dep="electron-builder"
          elif [[ "$title" == *"electron"* ]]; then
            dep="electron"
          fi

          if [ ! -z "$dep" ]; then
            echo "Closing dependabot PRs for $dep"
            gh pr list --author "app/dependabot" --json number,title | \
            jq -r --arg pkg "$dep" '.[] | select(.title | test("bump " + $pkg + " from"; "i")) | .number' | \
            xargs -I {} gh pr close {} --comment "Closed because a manual dependency upgrade for $dep is in progress."
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
