name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_call:
  workflow_dispatch:
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v5
      with:
        node-version: lts/*
    - name: Install deps
      run: npm install
      working-directory: simpliplay
    - name: Install Playwright browser(s)
      run: npx playwright install --with-deps
      working-directory: simpliplay
    - name: Run Playwright tests
      run: npm install playwright && npx playwright test
      working-directory: simpliplay
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
      #working-directory: simpliplay
