name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_call:
  workflow_dispatch:
jobs:
  test:
    if: github.actor != 'dependabot[bot]'
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v5
      with:
        node-version: lts/*
    - name: Install deps
      run: |
        npm install && npm install playwright --save-dev && npx playwright install --with-deps && sudo apt-get install xvfb
      working-directory: simpliplay
    - name: Run Playwright tests
      run: |
        xvfb-run node tests/basic-test.spec.js
      working-directory: simpliplay
    - uses: actions/upload-artifact@v6
      if: ${{ always() }}
      with:
        name: test-screenshots
        path: |
          simpliplay/intro.png
          simpliplay/played_media.png
        retention-days: 7
