name: Publish to Snap Store

on:
  workflow_dispatch:
    inputs:
      channel:
        description: 'Channel to release to'
        required: true
        default: 'edge'
        type: choice
        options: [edge, stable]

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: snap-upload
    steps:
     # this stops git from whining (phew)
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download all Snaps
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: snapcore/action-publish@v1 # REMEMBER thisssss!!!!!!!!
        run: |
          mkdir -p final-snaps
          # pulls all the snaps
          gh run download --dir final-snaps --pattern "*-snap"
          
      - name: Install snapcraft CLI
        run: sudo snap install snapcraft --classic
        
      - name: Publish to Snap Store
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
        run: |
          # well, if no snaps are found, everything will freak out
          shopt -s globstar nullglob

          snaps=(final-snaps/**/*.snap)

          if [ ${#snaps[@]} -eq 0 ]; then
            echo "No snaps found in final-snaps/, this is probably an issue with the yaml"
            exit 0
          fi
          
          for snap_file in "${snaps[@]}"; do
              echo "Uploading: $snap_file"
              snapcraft upload "$snap_file" --release ${{ github.event.inputs.channel }}
          done
