name: Publish to Snap Store

on:
  workflow_dispatch:
    inputs:
      channel:
        description: 'Channel to release to'
        required: true
        default: 'edge'
        type: choice
        options: [edge, stable]

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: snap-upload
    steps:
     # this stops git from whining (phew)
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download all Snaps
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p final-snaps
          # pulls all the snaps
          gh run download --dir final-snaps --pattern "*-snap"

      - name: Publish to Snap Store
        # use the official snapcore action
        uses: snapcore/action-publish@v1
        # its way better btw
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
        with:
          # find all the snaps
          snap: final-snaps/**/*.snap
          release: ${{ github.event.inputs.channel }}
