name: Publish to winget

on:
  workflow_call:
  workflow_dispatch:
  
jobs:
  build-winget:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Install deps
        run: npm ci
        working-directory: simpliplay

      - name: Build installer
        shell: bash
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: false
        run: | 
          npx electron-builder --win --x64 --arm64
          rm -f dist/SimpliPlay-win-setup.exe
          mv dist/SimpliPlay-x64-win-setup.exe dist/SimpliPlay-x64-winget-setup.exe
          mv dist/SimpliPlay-arm64-win-setup.exe dist/SimpliPlay-arm64-winget-setup.exe
        working-directory: simpliplay

      - name: Create pre-release for winget build
        uses: softprops/action-gh-release@9ed3cf9a6863b31f005d951c8d19de20628cf4eb
        with:
          tag_name: "winget-${{ github.run_number }}"
          name: "SimpliPlay desktop (winget-${{ github.run_number }})"
          draft: false
          prerelease: true
          files: |
            simpliplay/dist/SimpliPlay-x64-winget-setup.exe
            simpliplay/dist/SimpliPlay-arm64-winget-setup.exe
          token: ${{ secrets.GITHUB_TOKEN }}
          
  publish-winget:
    runs-on: ubuntu-latest
    needs: build-winget
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        
      - name: Parse version num
        id: ver-num
        run: |
          # search from main.js
          version=$(awk -F"['\"]" '/let version/ {print $2}' main.js)
          
          # fail if it wasn't found
          if [ -z "$version" ]; then
            echo "error: could not find version in main.js" >&2
            exit 1
          fi
          
          # if not failed, pass out to next job
          echo "version=$version" >> "$GITHUB_OUTPUT"
        working-directory: simpliplay

      - name: Create new release tag name
        id: winget_release
        run: |
          current_tag=$(git describe --tags --match="winget-*" --abbrev=0 2>/dev/null || echo "winget-X")
          echo "Current winget release: $current_tag"
          current_digit=${current_tag#winget-}
          new="winget-$((current_digit + 1))"
          echo "New release tag will be $new"
          echo "newtag=$new" >> $GITHUB_OUTPUT

      - name: Publish to Winget
        uses: vedantmgoyal9/winget-releaser@7bd472be23763def6e16bd06cc8b1cdfab0e2fd5 #v2
        with:
          identifier: AnirudhSevugan.SimpliPlay
          token: ${{ secrets.WINGET_PAT }}
          release-tag: ${{ steps.winget_release.outputs.newtag }} # release tag where winget setup exe is
          version: ${{ steps.ver-num.outputs.version }} # ver num from main release tag
          release-notes-url: https://github.com/A-Star100/simpliplay-desktop/releases/tag/release-${{ steps.ver-num.outputs.version }}
          installers-regex: '\.exe$' # only exe files
