name: Publish to MS Store

on:
  workflow_call:
  workflow_dispatch:
  
jobs:
  publish-msstore:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Install deps
        run: npm ci
        working-directory: simpliplay

      - name: Patch for MS Store
        shell: bash
        run: |
          # get version from main.js
          # that github-actions bot did
          version=$(sed -nE "s/.*version\s*[:=]\s*['\"]([0-9.]+)['\"].*\r?/\1/p" main.js)
          echo "Version being used for buildVersion arg: $version"
          
          # then have the main package.json version be one more
          jq --arg winVer "$version" --arg storeVer "$ms_store_version" '
            .version = (.version | split(".") | .[-1] = (.[-1] | tonumber + 1 | tostring) | join(".")) |
            .build.buildVersion = $winVer |
            .build.win = {
              "target": ["appx"]
            } |
            .build.appx = {
              "version": $storeVer,
              "identityName": "AnirudhSevugan.SimpliPlay",
              "publisher": "CN=980A5BA5-E457-4289-89D8-1E46A33B1D3E",
              "publisherDisplayName": "Anirudh Sevugan",
              "displayName": "SimpliPlay (PC)"
            }
          ' package.json > package.json.tmp

          # display json for debug now 
          cat package.json | jq '.'
        working-directory: simpliplay

      - name: Build installer
        shell: bash
        run: | 
          npx electron-builder --win --x64 --arm64
          mv dist/SimpliPlay-x64-*.appx dist/SimpliPlay-x64-msstore.appx
          mv dist/SimpliPlay-arm64-*.appx dist/SimpliPlay-arm64-msstore.appx
        working-directory: simpliplay

      - uses: microsoft/microsoft-store-apppublisher@v1.3
      - run: msstore reconfigure --tenantId ${{ secrets.PARTNER_CENTER_TENANT_ID }} --sellerId ${{ secrets.PARTNER_CENTER_SELLER_ID }} --clientId ${{ secrets.PARTNER_CENTER_CLIENT_ID }} --clientSecret ${{ secrets.PARTNER_CENTER_CLIENT_SECRET }}
      - run: msstore apps list
