name: Publish to winget

on:
  workflow_call:
  workflow_dispatch:
  
jobs:
  build-winget:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Install deps
        run: npm install
        working-directory: simpliplay

      - name: Patch for winget
        shell: bash
        run: |
          # get version from main.js
          # that github-actions bot did
          version=$(grep -oE "version\s*[:=]\s*['\"][0-9]+\.[0-9]+\.[0-9]+\.[0-9]+['\"]" main.js | grep -oE "[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+")
          echo "Version being used for buildVersion arg: $version"
          
          # then have the main package.json version be one more
          # so winget doesn't add Manifest-AppsAndFeaturesVersion-Error label
          jq --arg winVer "$version" '
            .version = (.version | split(".") | .[-1] = (.[-1] | tonumber + 1 | tostring) | join("."))
            | .build.buildVersion = $winVer 
            | .build.nsis += { 
                "oneClick": true, 
                "allowToChangeInstallationDirectory": false, 
                "perMachine": false, 
                "deleteAppDataOnUninstall": false 
              } 
          ' package.json > package.json.tmp   
          mv package.json.tmp package.json

          # display json for debug now 
          cat package.json | jq '.'
        working-directory: simpliplay

      - name: Build installer
        shell: bash
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: false
        run: | 
          npx electron-builder --win --x64 --arm64
          rm -f dist/SimpliPlay-win-setup.exe
          mv dist/SimpliPlay-x64-win-setup.exe dist/SimpliPlay-x64-winget-setup.exe
          mv dist/SimpliPlay-arm64-win-setup.exe dist/SimpliPlay-arm64-winget-setup.exe
        working-directory: simpliplay

      - name: Create pre-release for winget build
        uses: softprops/action-gh-release@9ed3cf9a6863b31f005d951c8d19de20628cf4eb
        with:
          tag_name: "winget-${{ github.run_number }}"
          name: "SimpliPlay desktop (winget-${{ github.run_number }})"
          draft: false
          prerelease: true
          files: |
            simpliplay/dist/SimpliPlay-x64-winget-setup.exe
            simpliplay/dist/SimpliPlay-arm64-winget-setup.exe
          token: ${{ secrets.GITHUB_TOKEN }}
          
  publish-winget:
    runs-on: ubuntu-latest
    needs: build-winget
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        
      - name: Parse version num
        id: ver-num
        run: |
          # search from main.js
          version=$(grep -oE 'let version\s*=\s*["'\''][^"'\'']+["'\'']' main.js | sed -E 's/.*["'\'']([^"'\'']+)["'\'']/\1/')
          
          # fail if it wasn't found
          if [ -z "$version" ]; then
            echo "error: could not find version in main.js" >&2
            exit 1
          fi
          
          # if not failed, pass out to next job
          echo "version=$version" >> "$GITHUB_OUTPUT"
        working-directory: simpliplay

      - name: Publish to Winget
        uses: vedantmgoyal9/winget-releaser@7bd472be23763def6e16bd06cc8b1cdfab0e2fd5 #v2
        with:
          identifier: AnirudhSevugan.SimpliPlay
          token: ${{ secrets.WINGET_PAT }}
          release-tag: winget-${{ github.run_number }} # release tag where winget setup exe is
          version: ${{ steps.ver-num.outputs.version }} # ver num from main release tag
          release-notes-url: https://github.com/A-Star100/simpliplay-desktop/releases/tag/release-${{ steps.ver-num.outputs.version }}
          installers-regex: '\.exe$' # only exe files

      - name: Add on-behalf-of at end of PR comment
        env:
          run_id: ${{ github.run_id }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # try wait for 15s so the PR can be found
          sleep 15
          
          # use filters to find PR
          pr_num=$(gh pr list -R microsoft/winget-pkgs -s open -A "[anirudhsevugan-bot]" -L 1 --json number -q '.[0].number')
          if [ "$pr_num" = "null" ] || [ -z "$pr_num" ]; then
            echo "No open PR was found, has it been merged already? Please check for open PRs and check for any issues in the workflow."
            exit 0
          fi
          
          # add workflow url
          workflow_url="https://github.com/A-Star100/simpliplay-desktop/actions/runs/${run_id}"
          
          # edit PR comment
          gh pr edit "$pr_num" -R microsoft/winget-pkgs --body "$(gh pr view "$pr_num" -R microsoft/winget-pkgs --json body -q '.body') \n
           *On behalf of @A-Star100 via [this workflow run]($workflow_url)*"
        continue-on-error: true
