name: Publish to Snap Store
#todo: possibly refactor
on:
  workflow_dispatch:
    inputs:
      channel:
        description: 'Channel to release to'
        required: true
        default: 'edge'
        type: choice
        options: [edge, stable, beta, candidate]
      arches:
        description: 'Arches to publish for'
        required: true
        default: 'all'
        type: choice
        options: [x64, arm64, armv7, all]
  workflow_call:
    inputs:
      channel:
        type: string
        required: true
      arches:
        type: string
        required: false

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #7.0.1
      - name: Download all Snaps
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p final-snaps
          # pulls all the snaps
          gh run download --dir final-snaps --pattern "*-snap"

      - name: Setup Snapcraft
        run: | 
          sudo snap install snapcraft --classic --channel=latest/stable
          echo "/snap/bin" >> $GITHUB_PATH

      - name: Publish to Snap Store
        shell: bash
        env:
          SNAPCRAFT_STORE_AUTH: candid
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
          channel: ${{ github.event.inputs.channel }}
          arch: ${{ github.event.inputs.arches }}
        run: |
          echo "Publishing snaps to: $channel"
          echo "Publishing for $arch architecture(s)"
          base="final-snaps"

          # check for arches input
          if [[ "$arch" == "x64" ]]; then
              valid=("linux-x64-snap")  
          elif [[ "$arch" == "arm64" ]]; then
              valid=("linux-arm64-snap")
          elif [[ "$arch" == "armv7" ]]; then
              valid=("linux-armv7l-v2-snap")
          else
              valid=("linux-x64-snap" "linux-arm64-snap" "linux-armv7l-v2-snap")  
          fi

          for artifact in "${valid[@]}"; do
            subdir="$base/$artifact"
            
            if [ -d "$subdir" ]; then
              echo "Checking artifact folder: $subdir"
              find "$subdir" -name "*.snap" | while read -r snap_file; do
                echo "Uploading $snap_file to $channel"
                snapcraft upload "$snap_file" --release "$channel"
              done
            else
              echo "An artifact wasn't found... $artifact was expected at $subdir"
              echo "Please fix the file structure and try again"
            fi
          done
