name: Publish to Snap Store

on:
  workflow_dispatch:
    inputs:
      channel:
        description: 'Channel to release to'
        required: true
        default: 'edge'
        type: choice
        options: [edge, stable, beta, canary]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
     # this stops git from whining (phew)
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download all Snaps
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p final-snaps
          # pulls all the snaps
          gh run download --dir final-snaps --pattern "*-snap"

      - name: Setup Snapcraft
        run: | 
          sudo snap install snapcraft --classic --channel=latest/stable
          echo "/snap/bin" >> $GITHUB_PATH

      - name: Publish to Snap Store
        shell: bash
        env:
          SNAPCRAFT_STORE_AUTH: candid
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
          TARGET_CHANNEL: ${{ github.event.inputs.channel }}
        run: |
          echo "Target channel: $TARGET_CHANNEL"
          
          BASE_DIR="final-snaps"
          
          VALID_ARTIFACTS=("linux-x64-snap" "linux-arm64-snap" "linux-armv7l-v2-snap")

          for artifact in "${VALID_ARTIFACTS[@]}"; do
            SUBDIR="$BASE_DIR/$artifact"
            
            if [ -d "$SUBDIR" ]; then
              echo "Checking artifact folder: $SUBDIR"
              find "$SUBDIR" -name "*.snap" | while read -r snap_file; do
                echo "Uploading: $snap_file to $TARGET_CHANNEL"
                snapcraft upload "$snap_file" --release "$TARGET_CHANNEL"
              done
            else
              echo "Artifact not found: $artifact (Expected at $SUBDIR)"
            fi
          done
