name: Publish to MS Store

on:
  workflow_call:
  workflow_dispatch:
  
jobs:
  publish-msstore:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Remove win section
        shell: bash
        run: |
          jq 'del(.build.win)' package.json > tmp.json && mv tmp.json package.json
        working-directory: simpliplay

      - name: Patch out update check
        shell: bash
        run: |
           chmod +x .github/workflows/patches/remove_update_check.sh
           .github/workflows/patches/remove_update_check.sh

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Install deps
        run: npm ci
        working-directory: simpliplay

      - name: Build appx
        shell: bash
        run: | 
          npx electron-builder --win appx --x64 --arm64
          ls dist/ # debug
          shopt -s extglob # add extendedglob
          mv dist/SimpliPlay*arm64.appx dist/SimpliPlay-arm64-msstore.appx
          mv dist/SimpliPlay!(*msstore*).appx dist/SimpliPlay-x64-msstore.appx
        working-directory: simpliplay
          
      - uses: actions/upload-artifact@v6
        with:
           name: windows-x64-appx
           path: simpliplay/dist/SimpliPlay-x64-msstore.appx
           
      - uses: actions/upload-artifact@v6
        with:
           name: windows-arm64-appx
           path: simpliplay/dist/SimpliPlay-arm64-msstore.appx

      # - name: Configure MS Store CLI
      #   uses: microsoft/microsoft-store-apppublisher@v1.3
      #   continue-on-error: true
        
      # - name: Reconfigure store credentials 
      #   run: |
      #       msstore reconfigure ` 
      #         --tenantId ${{ secrets.MS_TENANT_ID }} ` 
      #         --sellerId ${{ secrets.MS_SELLER_ID }} ` 
      #         --clientId ${{ secrets.MS_CLIENT_ID }} ` 
      #         --clientSecret ${{ secrets.MS_APPLICATION }} 
      #   continue-on-error: true
 
      # - name: Publish Appx
      #   run: |
      #     msstore publish 'SimpliPlay_universal.appxbundle' -id 9NZK5K3P1T6M
      # appx bundle is scrapped for now
      #   working-directory: simpliplay/dist
      #   continue-on-error: true
