name: Release

on:
  workflow_dispatch:
    inputs:
      snap_channel:
        description: 'Snap Store release channel'
        required: true
        default: 'edge'
        type: choice
        options: [edge, stable, beta, canary]
      snap_arches:
        description: 'Snap Store architectures to publish for'
        required: true
        default: 'all'
        type: choice
        options: [x64, arm64, armv7, all]
      stores:
        description: "Storefronts (doesn't include GitHub Releases obviously) to build and/or publish for"
        required: true
        default: 'all'
        type: choice
        options: [snapstore, msstore, winget, all, none]

jobs:
  build-linux:
    uses: ./.github/workflows/build-linux.yml

  build-macos:
    uses: ./.github/workflows/build-macos.yml

  build-windows:
    uses: ./.github/workflows/build-win.yml

  # needs these inputs to decide
  publish-snap:
    if: inputs.stores == 'snapstore' || inputs.stores == 'all'
    needs: [build-linux]
    uses: ./.github/workflows/publish-snap.yml
    with:
      channel: ${{ inputs.snap_channel }}
      arches: ${{ inputs.snap_arches }}
    secrets: inherit

  # winget ci builds its own version
  build-winget:
    if: inputs.stores == 'winget' || inputs.stores == 'all'
    permissions:
      contents: write
    uses: ./.github/workflows/build-winget.yml
    secrets: inherit

  # publish-winget:
  #   needs: [build-winget]
  #   uses: ./.github/workflows/publish-winget.yml
  #   secrets: inherit

  build-msstore:
    if: inputs.stores == 'msstore' || inputs.stores == 'all'
    permissions:
      contents: write
    uses: ./.github/workflows/publish-msstore.yml

  playwright-test:
    uses: ./.github/workflows/playwright.yml

  # uploads existing builds and runs after basic retest in CI
  draft-release:
    needs: [build-linux, build-macos, build-windows, playwright-test]
    permissions:
      contents: write
    uses: ./.github/workflows/draft-release.yml
    secrets: inherit
